/* DOM element references, resolved once at module load. Every card/filter/
 * workspace module reads from this shared object rather than re-querying the
 * DOM. Extracted from app.js per MODULARIZATION.md v1.3.0 §2/§3 step 1 — not
 * one of the brief's named modules, but required: els is read from nearly
 * every function in the file (~230 call sites in the original app.js).
 */

export const els = {
  category: document.getElementById("category-select"),
  season: document.getElementById("season-select"),
  position: document.getElementById("position-select"),
  xMetric: document.getElementById("x-metric-select"),
  yMetric: document.getElementById("y-metric-select"),
  threshold: document.getElementById("threshold-slider"),
  thresholdNumber: document.getElementById("threshold-number"),
  applyBtn: document.getElementById("apply-filters"),
  savePngBtn: document.getElementById("save-png-btn"),
  thresholdFieldLabel: document.getElementById("threshold-field-label"),
  labelsToggle: document.getElementById("labels-toggle"),
  logosToggle: document.getElementById("logos-toggle"),
  teamsControl: document.querySelector(".control-teams"),
  teamsBtn: document.getElementById("teams-toggle-btn"),
  teamsSummary: document.getElementById("teams-select-summary"),
  teamsDropdown: document.getElementById("teams-dropdown"),
  teamsChecklist: document.getElementById("teams-checklist"),
  teamsSelectAll: document.getElementById("teams-select-all"),
  teamsSelectNone: document.getElementById("teams-select-none"),
  playersControl: document.getElementById("players-control"),
  playersResetBtn: document.getElementById("players-reset-btn"),
  playersBtn: document.getElementById("players-toggle-btn"),
  playersSummary: document.getElementById("players-select-summary"),
  playersPanel: document.getElementById("players-panel"),
  playersField: document.getElementById("players-field"),
  playersChips: document.getElementById("players-chips"),
  playersInput: document.getElementById("players-input"),
  playersDropdown: document.getElementById("players-dropdown"),
  chart: document.getElementById("chart"),
  chartPanel: document.querySelector(".chart-panel"),
  emptyState: document.getElementById("empty-state"),
  logoPreload: document.getElementById("logo-preload"),
  filtersToggle: document.getElementById("toggle-filters"),
  filtersDrawer: document.getElementById("filters-drawer"),
  scoutCards: document.getElementById("scout-cards"),
  scoutEmptyHint: document.getElementById("scout-empty-hint"),
  scoutCardTemplate: document.getElementById("scout-card-template"),
  mergeCardTemplate: document.getElementById("merge-card-template"),
  linemateCardTemplate: document.getElementById("linemate-card-template"),
  mergeConfirmOverlay: document.getElementById("merge-confirm-overlay"),
  mergeConfirmCancel: document.getElementById("merge-confirm-cancel"),
  mergeConfirmClear: document.getElementById("merge-confirm-clear"),
  workspaceNoticeOverlay: document.getElementById("workspace-notice-overlay"),
  workspaceNoticeBody: document.getElementById("workspace-notice-body"),
  workspaceNoticeOk: document.getElementById("workspace-notice-ok"),
  // Pinned Players (BLUEPRINT_PinnedPlayers.md) — see
  // renderPlayerCardsSpace() in app.js.
  playerCardsSpace: document.getElementById("player-cards-space"),
  pcsQuotaLabel: document.getElementById("pcs-quota-label"),
  pcsInspectBtn: document.getElementById("pcs-inspect-btn"),
  pcsPanel: document.getElementById("pcs-panel"),
  pcsSinglesList: document.getElementById("pcs-singles-list"),
  pcsSinglesEmpty: document.getElementById("pcs-singles-empty"),
  pcsMergedList: document.getElementById("pcs-merged-list"),
  pcsMergedEmpty: document.getElementById("pcs-merged-empty"),
  // Single Cards add-search (v1.2.0 §4) — Pinned Players' only entry point.
  pcsAddInput: document.getElementById("pcs-add-input"),
  pcsAddDropdown: document.getElementById("pcs-add-dropdown"),
  // Merged Cards "Create" button + its popup (v1.2.0 §5).
  pcsCreateBtn: document.getElementById("pcs-create-btn"),
  mergeCreateOverlay: document.getElementById("merge-create-overlay"),
  mergeCreateMembers: document.getElementById("merge-create-members"),
  mergeCreateInput: document.getElementById("merge-create-input"),
  mergeCreateDropdown: document.getElementById("merge-create-dropdown"),
  mergeCreateMessage: document.getElementById("merge-create-message"),
  mergeCreateCancel: document.getElementById("merge-create-cancel"),
  mergeCreateSubmit: document.getElementById("merge-create-submit"),
  // Merge Card membership editor popup.
  mergeEditOverlay: document.getElementById("merge-edit-overlay"),
  mergeEditMembers: document.getElementById("merge-edit-members"),
  mergeEditInput: document.getElementById("merge-edit-input"),
  mergeEditDropdown: document.getElementById("merge-edit-dropdown"),
  mergeEditMessage: document.getElementById("merge-edit-message"),
  mergeEditDone: document.getElementById("merge-edit-done"),
};
